name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Copy .env
        run: cp .env.example .env

      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run Composer install
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "docker/bin/composer install"

      - name: Run post-create-project-cmd
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "docker/bin/composer run post-create-project-cmd"
      
      - name: Run checkk
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "docker/bin/composer run check"

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "docker/bin/composer test"

      - name: Stop and remove services
        if: always()
        run: docker-compose -f docker-compose.yml down
