name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  calendar-event-management-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Install mkcert
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-tools
          curl -L -o mkcert https://dl.filippo.io/mkcert/latest?for=linux/amd64
          chmod +x mkcert
          sudo mv mkcert /usr/local/bin/mkcert
          mkcert --version # Verify installation

      - name: Generate local CA and SSL certificates
        run: |
          mkcert -install
          mkcert -cert-file docker/nginx/ssl.pem -key-file docker/nginx/key.pem api.calendar-event-management.test

      - name: Build and start services
        env:
          DOCKER_SERVER_NAME: api.calendar-event-management.test
          DOCKER_MYSQL_LOCAL_PORT: 3306
          DOCKER_NGINX_LOCAL_PORT: 443
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Copy .env file
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "cp .env.example .env"

      - name: Run Composer install
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "composer install"

      - name: Generate application key
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "php artisan key:generate --ansi"

      - name: Run post-create-project-cmd
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "composer run post-create-project-cmd"

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml exec -T php-fpm-debug /bin/sh -c "composer test"

      - name: Stop and remove services
        if: always()
        run: docker-compose -f docker-compose.yml down
